### ISSUE TITLE
I cant convert the map 

### ISSUE THREAD

**Issue by sdadaw31231222** [SentientTurtle/RBXLX2VMF#3] opened 2023-04-03 13:51 UTC
![image](https://user-images.githubusercontent.com/129762501/229529889-6f7e2ba5-dca9-4262-b1e4-202c6b673fb4.png)

**Comment by sdadaw31231222** [comment] 2023-04-03 14:35
google.

**Comment by sdadaw31231222** [comment] 2023-04-03 19:29
bro? why u closed that

**Comment by SentientTurtle** [comment] 2023-04-03 21:55
I have closed #2 as it's a duplicate of this issue. (And you seem to be the person that opened it, on another account?)

The Google Chrome version you use is supported, so this appears to be a bug.

I've updated the web version to show the same log as the CLI version. Could you try again? You should be given a more useful error now.

**Comment by sdadaw31231222** [comment] 2023-04-04 17:32
Btw, i've downloadd 2 maps (from elemental adventures and 1 from avatar legacy when im trying to port it says  error: invalid XML the document does not have a root node"

**Comment by SentientTurtle** [comment] 2023-04-04 20:53
That error means your map file is empty, either 0kb in size or commented out. I cannot help you with export issues in the roblox editor.

Note the purpose for this tool is to aid in "greyboxing"/blockout map design, not porting of existing roblox games. 

There is no support for the "union" part geometry, meshes, or terrain features. Any map using them will fail to convert correctly, which includes most full "experiences" as released on roblox.

You also shouldn't be converting maps you do not have rights to use.

**Closed** 2023-04-08 19:42 UTC
