### ISSUE TITLE
Solids not loading

### ISSUE THREAD

**Issue by Amittere1** [SentientTurtle/RBXLX2VMF#5] opened 2023-05-24 08:04 UTC
![image](https://github.com/SentientTurtle/RBXLX2VMF/assets/109173080/db6ec13a-5b3a-4610-b78a-a8298c001ac5)

Hello im trying to load the map.vmf to hammer to convert it to bsp so i can play it in Garry's Mod
but its not working

**Comment by SentientTurtle** [comment] 2023-05-24 15:12
That is indeed an issue on the converter's side.

If this is a map you've made, could you share the (rbxlx) map file?  
Ideally, see if you can reproduce the issue with a small part of the map.

**Comment by SentientTurtle** [comment] 2023-05-25 14:45
There appear to be two issues here:

1. The VMF file has 'corrupt' solids because the map is too big. Source engine restricts maps to a width/height/depth of 32768 hammer units (At default scaling, roughly 2180 roblox units)
  Unfortunately, there is nothing I can do about that limitation. I will update the tool to provide a (soft) error in such cases.

2. The map is offset from the origin. The tool currently doesn't correct for this, so maps that are far off-center will be generated outside the source engine limits.
  A fix for this will be rolled out shortly.

The map you wish to convert exceeds the size limits even after correcting it's position; It cannot be converted at default scale. And the large size of the map will lead to poor performance in the source engine.

**Closed by SentientTurtle** 2023-05-25 14:45 UTC
